Basic UI
Haywayaheadshot/school-library pull request #4
Opened 2023-01-06 22:40 UTC by Haywayaheadshot

2023-01-06 23:25 UTC, jerryowusu requested changes
Hi @Haywayaheadshot , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![so close](https://user-images.githubusercontent.com/65233860/211116169-878f13f5-0a14-45fe-bb13-fd66809a9f76.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Great effort so far :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 23:25 UTC, jerryowusu commented on app.rb
> +  end
Your app is currently not storing the data anywhere so it closes when you create a person or book. As a result it becomes difficult to go ahead and create  rental or even list available books/people. 

- [ ] Kindly consider initializing the books, people, and rentals and storing them in an array to fix this issue. 
- [ ] You should also check and make sure to the app can list all books and able to undergo all functions successfully. :pray: 

![Screenshot from 2023-01-06 23-14-12](https://user-images.githubusercontent.com/65233860/211115565-84d378f8-4b65-4934-880b-94b1dd4e4d51.png)

![Screenshot from 2023-01-06 23-14-19](https://user-images.githubusercontent.com/65233860/211115569-2c525b39-e923-420d-ade2-ccfd95d61a09.png)

2023-01-06 23:25 UTC, jerryowusu commented on app.rb
> +  end
The app abruptly closes when there is no book or people availabe. This is not supposed to be so, it should allow you to create a book or person and also check again to create rentals. Kindly check and fix this issue. 

![Screenshot from 2023-01-06 23-23-31](https://user-images.githubusercontent.com/65233860/211115959-9faf9a8d-2281-4101-b069-b7888252797b.png)


![Screenshot from 2023-01-06 23-23-22](https://user-images.githubusercontent.com/65233860/211115950-c9660778-b3cc-4738-9821-8e7f3d6d2b79.png)

2023-01-07 00:30 UTC, Haywayaheadshot commented
@jerryowusu Thank you for reviewing my project

2023-01-07 01:54 UTC, mwanawabangona approved these changes
Hi @Haywayaheadshot 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-07 01:57 UTC, Haywayaheadshot commented
@mwanawabangona Thank you for reviewing my project. Have a great weekend

2023-01-07 02:01 UTC, merged